# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 16:01
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Landmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('non_bldg', models.CharField(max_length=254)),
                ('last_action', models.CharField(max_length=254)),
                ('historic_district', models.CharField(max_length=254)),
                ('secnd_bldg', models.FloatField()),
                ('objectid', models.FloatField()),
                ('calen_date', models.CharField(max_length=254)),
                ('block', models.FloatField()),
                ('date_designated', models.DateField()),
                ('time_designated', models.CharField(max_length=254)),
                ('most_current', models.FloatField()),
                ('vacant_lot', models.FloatField()),
                ('boundaries', models.CharField(max_length=254)),
                ('bin_number', models.FloatField()),
                ('pluto_addr', models.CharField(max_length=254)),
                ('status_not', models.CharField(max_length=254)),
                ('status', models.CharField(max_length=254)),
                ('lot', models.FloatField()),
                ('lm_type', models.CharField(max_length=254)),
                ('other_hear', models.CharField(max_length=254)),
                ('desig_addr', models.CharField(max_length=254)),
                ('lp_number', models.CharField(max_length=254)),
                ('public_hea', models.CharField(max_length=254)),
                ('borough_id', models.CharField(max_length=254)),
                ('count_bldg', models.FloatField()),
                ('bbl', models.CharField(max_length=254)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
