# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0004_parcel_centroid'),
        ('landmarks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='landmark',
            name='parcel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='landmark_object', to='parcels.Parcel'),
        ),
    ]
