# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 18:02
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    operations = [
        migrations.CreateModel(
            name='PostOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('streetname', models.CharField(max_length=254)),
                ('url', models.CharField(max_length=254)),
                ('housenum', models.CharField(max_length=254)),
                ('bin', models.FloatField()),
                ('zip', models.CharField(max_length=254)),
                ('city', models.CharField(max_length=254)),
                ('bbl', models.CharField(max_length=254)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('parcel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parcels.Parcel')),
            ],
        ),
    ]
