# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-09 20:00
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postoffices', '0001_squashed_0002_auto_20160516_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='postoffice',
            name='ownerfixed',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='postoffice',
            name='public',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='postoffice',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=4326),
        ),
    ]
