# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-14 18:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communitydistricts', '0002_auto_20150430_0003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communitydistrictdetails',
            options={'verbose_name': 'community district details', 'verbose_name_plural': 'community district details'},
        ),
    ]
