# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 17:56
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=254)),
                ('communityb', models.CharField(max_length=254)),
                ('nys_senate', models.CharField(max_length=254)),
                ('signname', models.CharField(max_length=254)),
                ('zipcode', models.CharField(max_length=254)),
                ('us_congres', models.CharField(max_length=254)),
                ('gispropnum', models.CharField(max_length=254)),
                ('borough', models.CharField(max_length=254)),
                ('waterfront', models.CharField(max_length=254)),
                ('nys_assemb', models.CharField(max_length=254)),
                ('councildis', models.CharField(max_length=254)),
                ('acres', models.FloatField()),
                ('typecatego', models.CharField(max_length=254)),
                ('address', models.CharField(max_length=254)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
