# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 17:17
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bbl', models.CharField(max_length=254)),
                ('housenum', models.CharField(max_length=254)),
                ('borocode', models.FloatField()),
                ('bin', models.FloatField()),
                ('zip', models.CharField(max_length=254)),
                ('city', models.CharField(max_length=254)),
                ('name', models.CharField(max_length=254)),
                ('system', models.CharField(max_length=254)),
                ('url', models.URLField()),
                ('streetname', models.CharField(max_length=254)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
