# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 20:07
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0003_auto_20141024_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
